apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-go-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-go
  template:
    metadata:
      labels:
        app: myapp-go
    spec:
      containers:
      - name: myapp-go
        image: tannuahuja14/myapp-go:latest
        ports:
        - containerPort: 3030

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-go-service
spec:
  selector:
    app: myapp-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: LoadBalancer
